sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"

addons:
  apt:
    sources:
    - sourceline: 'ppa:hvr/ghcjs'
    update: true

matrix:
  include:
  - ghcjs: 8.4.4

install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - cabal update
  - cabal build --enable-tests --enable-benchmarks

script:
  - echo 'No tests'

notifications:
  email: false
