sudo: true
language: haskell

git:
  depth: 5

cabal: "3.0"

cache:
  directories:
  - "$HOME/.cabal/store"


matrix:
  include:
  - ghc: 8.4.4
    env: GHCVER='8.4.4' CABALVER='head'
    os: linux
    addons:
      apt:
        sources:
        - hvr-ghcjs
        packages:
        - ghcjs-8.4.3
        - cabal-install-head


install:
  # HLint check
  - curl -sSL https://raw.github.com/ndmitchell/neil/master/misc/travis.sh | sh -s -- hlint .

  - cabal update
  - cabal build --enable-tests --enable-benchmarks

script:
  - echo 'No tests'

notifications:
  email: false
